steps:
  # 1. Exécution des tests Maven
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['test']
    dir: '.'
    id: 'run-maven-tests'

  # 2. Analyse SonarQube
  # Le compte de service Cloud Build doit avoir le rôle 'Secret Manager Secret Accessor' pour accéder aux secrets
  - name: 'gcr.io/cloud-builders/mvn'
    args:
      - 'sonar:sonar'
      - '-Dsonar.projectKey=league-of-legends-api'
      - '-Dsonar.organization=$${_SONAR_ORGANIZATION}'
      - '-Dsonar.host.url=$${_SONAR_HOST_URL}'
      - '-Dsonar.token=$${_SONAR_TOKEN}'
    dir: '.'
    secretEnv: ['_SONAR_TOKEN']
    waitFor: ['run-maven-tests']
    id: 'run-sonarqube-analysis'

  # 3. Construction de l’image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${COMMIT_SHA}'
      - '.'
    dir: '.'
    waitFor: ['run-sonarqube-analysis']
    id: 'build-docker-image'

  # 4. Push de l'image Docker vers Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${COMMIT_SHA}'
    waitFor: ['build-docker-image']
    id: 'push-to-artifact-registry'

  # 5. Déploiement sur Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${COMMIT_SHA}'
      - '--platform=managed'
      - '--region=${_CLOUD_RUN_REGION}'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--set-secrets=API_KEY=lol-api-key:latest,MONGO_DATABASE_URL=mongo-database-url:latest'
    waitFor: ['push-to-artifact-registry']
    id: 'deploy-to-cloud-run'

secrets:
  - id: _SONAR_TOKEN
    version: projects/${PROJECT_ID}/secrets/sonar-token/versions/latest
  - id: _SONAR_HOST_URL
    version: projects/${PROJECT_ID}/secrets/sonar-host-url/versions/latest
  - id: _SONAR_ORGANIZATION
    version: projects/${PROJECT_ID}/secrets/sonar-organization/versions/latest

substitutions:
  _GAR_LOCATION: europe-west9
  _REPOSITORY: eu.gcr.io
  _IMAGE_NAME: league-of-legends-api
  _SERVICE_NAME: league-of-legends-api-service
  _CLOUD_RUN_REGION: europe-west9