server:
  port: 8080
spring:
  application:
    name: league-of-legends-api
  web:
    resources:
      add-mappings: false
  data:
    mongodb:
      uri: ${MONGO_DATABASE_URL}LeagueOfLegends
    web:
      pageable:
        default-page-size: 30
league-of-legends:
  api-key: ${API_KEY}